server:
  port: 8085
  servlet:
    context-path: /jobseekerservice  # Match the curl request
spring:
  application:
    name: jobseeker-service
  datasource:
    url: jdbc:postgresql://localhost:5432/JobSeekerService?createDatabaseIfNotExist=true
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ganjiharish9662@gmail.com
    password: iyrw ojac qaee dtua
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework.security: DEBUG
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
